logging.level:
    com:
      cda: debug
    org:
      hibernate: 
        SQL: trace
      springframework:
        web: info

spring:
  datasource:
    username: todolifeuser
    password: pwd
    url: jdbc:postgresql://localhost:5432/paytondebug
    initialization-mode: always
  jpa.hibernate.ddl-auto : create-drop

