logging.level:
    com:
      cda: debug
    org:
      hibernate: 
        SQL: trace
      springframework:
        web: info
        
jwt.key : cda-cle-secrete 

spring:
  datasource:
    username: todolifeuser
    password: pwd
    url: jdbc:postgresql://localhost:5432/todolife
    initialization-mode: always
  jpa.hibernate.ddl-auto : create-drop



